default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: rails-watch-list_development

test:
  <<: *default
  database: rails-watch-list_testcurl https://cli-assets.heroku.com/install.sh | sh
heroku --version # It should display heroku/x.x.x
